import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib as mpl
import numpy as np
import os
import argparse
os.chdir(os.path.abspath(os.path.dirname(__file__)))

mpl.rcParams["savefig.directory"] = ""
plt.rcParams.update({'font.size': 30})
plt.rc('legend', fontsize=25)
plt.rc('figure', titlesize=36)
plt.rc('axes', titlesize=30) 
plt.rcParams['axes.grid'] = True
plt.rc('lines', linewidth=4)
plt.rcParams['axes.titlepad'] = 26
plt.rcParams['axes.labelsize'] = 30
plt.rc('xtick', labelsize=22)
plt.rc('ytick', labelsize=22) 







# Parse command-line..
description = '''Plots the observables in a data file generated by IPS.exe.
                 This only works for the default observables (centre of mass distances, mean-squared-displacement, kinetic temperature).
              '''
parser = argparse.ArgumentParser(description=description)

parser.add_argument('file', type=str, help='File holding the data.')
parser.add_argument("--title", type=str, default="", help="Title of the plot.")

args = parser.parse_args()

filename = args.file
title = args.title

# Load data.
arr = np.loadtxt(filename, delimiter=None, skiprows=1) 

times = arr[:,0]
COM_dist = arr[:,1]
msd = arr[:,2]
Tkin = arr[:,3]

# Create plot.
fig, ax = plt.subplots(3,1)

ax[0].plot(times, COM_dist)
ax[1].plot(times, msd)
ax[2].plot(times, Tkin)

ax[0].set_title("Mean Distance to Center Of Mass")
ax[1].set_title("Mean Squared Displacement")
ax[2].set_title("Kinetic Temperature")

ax[2].set_xlabel("Time")
if title:
    fig.suptitle(title)

plt.show()